#!/bin/sh
. ./configure
# versucht alle Dateien eines Projekts zu editieren, mit Parameter 'nv' sollen alle aufs aktuelle Datum gesetzt werden
ZD=viaufruf # speichere die Zahl der Aufrufe in Datei dieses Namens
FREQUENZ=5 # rufe gtags jedes 5. Mal auf

exportvars
einricht ctags "$CTAGS"
ctags *.cpp *.h
test -f $ZD || echo 1>$ZD; awk "BEGIN {print `cat $ZD`+1}">$ZD
(($(cat $ZD)%$FREQUENZ)) ||einricht gtags global; # in Fedora koennte gtags noch installiert werden muessen
einricht vim vim
# PR=vim;PK=$PR;still which $PR ||{ getIPR;[ $fed = 1 ] &&{ sudo yum update vim-minimal;};${IP_R}$PK&&{ test -f $UNF&&grep -q " $PK" $UNF||\
# printf "${UPR}$PK\nprintf \"\$blau%%s\$reset\" \"${UPR}$PK\"\nalias vi>$KR&&sudo unalias vi\necho \"alias vi>$KR&&sudo unalias vi\"\n">>$UNF;};}
# so waere es projektspezfisch
# `which vim || which vi` autofax.cpp autofax.h vgb.cpp DB.cpp DB.h kons.cpp kons.h -p -c "syntax on" -c "set number" -c "set autoindent" -c "set autoindent" -c "set tabstop=2" -c "set ignorecase" -c "set showmatch" -c "set magic" -c "set ruler" 
# DATEIEN="autofax.cpp autofax.h vgb.cpp DB.cpp DB.h kons.cpp kons.h man_en man_de Makefile install.sh viall .exrc"
# .. und so etwas allgemeiner

# wenn eiheitliche Versionsnummer gewuenscht
if [ "$1" = "nv" ]; then
# touch $DATEIEN
 mkdir -p res
 cp -a $DATEIEN res
 git rm --cached $DATEIEN
 git commit -m "nix"
 git add $DATEIEN
 git rm --cached vgb.cpp
 make opts && sudo make install && make git
else
`which vim || which vi` $DATEIEN -pNu .exrc
fi
